-- INSERT INTO NOTE(ID, TITLE, DESCRIPTION,OWNER) VALUES (99, 'First Note', 'Hello World!', 'sarah1');
-- INSERT INTO NOTE(ID, TITLE, DESCRIPTION,OWNER) VALUES (100, 'Second Note', 'Hello World!','sarah1');
-- INSERT INTO NOTE(ID, TITLE, DESCRIPTION,OWNER) VALUES (101, 'Third Note', 'Hello World!', 'sarah1');
-- INSERT INTO NOTE(ID, TITLE, DESCRIPTION, OWNER) VALUES(102, 'Kumar''s Note', 'Hello Guys!', 'kumar2');

INSERT INTO NOTE(ID, TITLE, DESCRIPTION, OWNER)
VALUES (99, 'First Note', 'Hello World!', 'sarah1') ON DUPLICATE KEY
UPDATE TITLE =
VALUES (TITLE), DESCRIPTION =
VALUES (DESCRIPTION), OWNER =
VALUES (OWNER);

INSERT INTO NOTE(ID, TITLE, DESCRIPTION, OWNER)
VALUES (100, 'Second Note', 'Hello World!', 'sarah1') ON DUPLICATE KEY
UPDATE TITLE =
VALUES (TITLE), DESCRIPTION =
VALUES (DESCRIPTION), OWNER =
VALUES (OWNER);

INSERT INTO NOTE(ID, TITLE, DESCRIPTION, OWNER)
VALUES (101, 'Third Note', 'Hello World!', 'sarah1') ON DUPLICATE KEY
UPDATE TITLE =
VALUES (TITLE), DESCRIPTION =
VALUES (DESCRIPTION), OWNER =
VALUES (OWNER);

INSERT INTO NOTE(ID, TITLE, DESCRIPTION, OWNER)
VALUES (102, 'Kumar''s Note', 'Hello Guys!', 'kumar2') ON DUPLICATE KEY
UPDATE TITLE =
VALUES (TITLE), DESCRIPTION =
VALUES (DESCRIPTION), OWNER =
VALUES (OWNER);
