DROP TABLE IF EXISTS NOTE;
CREATE TABLE IF NOT EXISTS NOTE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE       VARCHAR(256),
    DESCRIPTION VARCHAR(256),
    OWNER       VARCHAR(256) NOT NULL
);